class_name: RelatorioAnaliticoEmitido
json_data: '{
  "considerarVolumeFaturadoZero": true,
  "descrTipoCategoria": "string",
  "enquadramentoFaixaVolFaturado": true,
  "faixas": [
    {
      "ate": 0,
      "de": 0,
      "id": 0
    }
  ],
  "grupo": "string",
  "id": 0,
  "idCidade": 0,
  "idGrupo": 0,
  "idProduto": 0,
  "opcao": 0,
  "perFinal": "string",
  "perInicial": "string",
  "periodo": 0,
  "periodos": "string",
  "produto": "string",
  "seqPerFinal": 0,
  "seqPerInicial": 0,
  "tipoCategoria": 0
}'